### ISSUE TITLE
Category Tree

### ISSUE THREAD

**Issue by Michael-Reich** [responsiv/showcase-plugin#4]
Is it possible to change to plugin that a category tree works?

Like this:

```
Category 1
--Downcat 1
--Downcat 2
--Downcat 3
--Downcat 4
----Downcat 1
Category 2
--Downcat 1
--Downcat 2
----Downcat 1
----Downcat 2
```

Would be great to hear!

**Comment by daftspunk** [comment]
Will leave this open as a feature request. Thanks

**Comment by Michael-Reich** [comment]
Okey thank you, is it planned to implement the next time? Would even donate for that feature!
And are tags planned?

**Comment by daftspunk** [comment]
You are welcome to submit a [bounty for it here](https://www.bountysource.com/issues/35385986-category-tree). This will expedite the process and make it a priority.

**Comment by Hessel91** [comment]
I would like to use isotope libary to toggle the different categories on the same overview page. how can I do that?
