### ISSUE TITLE
showcaseCategories not working with custom Slug

### ISSUE THREAD

**Issue by Michael-Reich** [responsiv/showcase-plugin#6]
![bildschirmfoto 2017-03-31 um 21 31 24](https://cloud.githubusercontent.com/assets/10381330/24566349/709378b2-1659-11e7-9c59-b2123e9744ae.png)

I made a custom :slug for my showcaseCategories Component and wanted to display it in the sidebar to my Items. The only problem was that this just showed the link to the current Item Category not all Categoires.

**Comment by daftspunk** [comment]
This assertion doesn't make sense. The category slug should only really be used to set the active category. Make sure `Display empty categories` is ticked.

Please support the assertion by providing all the code (theme template file contents) you are using.
